language: python
python: 3.6.3

cache: false

stages:
  - test
  - moban
  - name: deploy
    if: type != pull_request

.moban: &moban
  python: 3.6
  stage: moban
  install: pip install moban~=0.5.0 gitfs2 pypifs
  script:
    - moban
    - git diff --exit-code

env:
  global:
    - ENCRYPTION_LABEL: "defac9b1fa56"
    - COMMIT_AUTHOR_EMAIL: "nobody@coala.io"

jobs:
  include:
    # This more closely emulates a forked build
    # However the git remote is not correct
    # Only a GH_TOKEN is required.
    - stage: test
      env: GL_TOKEN="" GCI_TOKEN="" OH_TOKEN=""
    # A proper build with the tokens available
    - stage: deploy
      after_success: ./.ci/deploy.sh
    - *moban
  allow_failures:
    - *moban

before_install:
  - printf '%s\n'
           "$(cat test-requirements.txt requirements.txt)"
           > requirements.txt
  - npm i -g jshint

script:
  - ./.ci/build.sh
  - rm -rf private/
  - pytest
  - coala --flush-cache --non-interactive -V

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
