# Generated by Django 2.1.7 on 2019-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180809_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='location',
            field=models.TextField(default=None, null=True),
        ),
    ]
