# Generated by Django 2.1.7 on 2019-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_contributor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='teams',
            field=models.ManyToManyField(related_name='contributors', to='data.Team'),
        ),
    ]
