# Generated by Django 2.1.7 on 2019-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField(verbose_name='Participation year')),
                ('project_topic', models.CharField(max_length=300, verbose_name='Project topic')),
                ('project_desc', models.TextField(max_length=2000, verbose_name='Project description')),
                ('accepted_proposal', models.URLField(verbose_name='Accepted proposal URL')),
                ('cEP', models.URLField(verbose_name='cEP merge request')),
                ('projects_mr', models.URLField(verbose_name='Merge Reeuest for adding project in coala projects')),
                ('project_url', models.URLField(verbose_name='GSoC Project URL')),
                ('image', models.URLField(null=True, verbose_name='Image URL')),
            ],
        ),
    ]
